<%@ page pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta name="description"
	content="A multi-page template generated by Tizen Web IDE" />
<title>抽奖</title>
<link href="${pageContext.request.contextPath }/css/bootstrap.min.css" rel="stylesheet" type="text/css"></link>
<%@include file='/jsp/head2.jsp'%>
<script type="text/javascript" src="${pageContext.request.contextPath }/jsp/page/voucher/jsp/js/browser.js"></script>
<style>
	#voucherInfo_name{
		font-size: 25px;
	}
	.press{
		color: transparent;
		-webkit-text-stroke: 1px black;
		font-size:24px;
		font-style: oblique;
		letter-spacing: 0.05em;
	}
	#hexiaodiv{
	  display:none;
	
	  z-index:9999;
	}
	#vouchershowdiv{ display:inline-block; position:relative; margin:50px; padding:20px; background:#fafafa; box-shadow:0 0 3px rgba(0, 0, 0, 0.2); -moz-border-radius:4px; border-radius:4px; color:rgba(0,0,0, 0.8); text-shadow:0 1px 0 #fff;}  
	#vouchershowdiv::before, #vouchershowdiv::after{ position:absolute; content:""; top:10px; bottom:15px; left:10px; width:50%; box-shadow:0 15px 10px rgba(0, 0, 0, 0.5); -webkit-transform: rotate(-3deg); -moz-transform:rotate(-3deg); -o-transform:rotate(-3deg); -ms-transform:rotate(-3deg); transform:rotate(-3deg); z-index:-1;}  
	#vouchershowdiv::after{ right:10px; left:auto; -webkit-transform:rotate(3deg); -moz-transform:rotate(3deg); -o-transform:rotate(3deg); -ms-transform:rotate(3deg); transform: rotate(3deg);}  
	#vouchershowdiv img{ vertical-align:bottom;} 
	body {height: 100%;}
	#right{
    position: fixed;
    bottom: 100px;
    width: 80px;
    height:40px;
   font-size:20px;
   line-height:40px;
    text-align: center;
    border: 0px solid #000;
    background-color:#C7E1F3;
    font-weight: bold;
    border-radius:10px;
    cursor: pointer;
	}
	#right{
	    right: 5px;
	}
#vouchershowdiv1{

position:absolute; 
width:100%; 
height:100%; 
background:url(${pageContext.request.contextPath }/jsp/page/lucky/jsp/images/jp.jpg);
background-size:100% 100%;
}
.sxs{
float:left;
position:absolute; 
width:100%; 
height:100%; 
background:url(${pageContext.request.contextPath }/jsp/page/lucky/jsp/images/dphx.jpg);
background-size:100% 100%;
margin-left: -8%;
padding-top: 19%;
	}

</style>
</head>
<body >
<div id="onediv">
	 <div class="container" id="vouchershowdiv1" >  
	 <div class="row" style="padding-top:62%">
	 <div class="col-xs-offset-1 col-xs-10">
		 <h3 class="text-center "><strong style="font-size: 26px;" id="lkuckyinfoname1"></strong></h3>
	 </div>
	 </div>
	 
	 <div class="row"  style="margin-top:5%">
	 <div class="col-xs-offset-1 col-xs-10">
		 <h2 class="text-center"><strong style="font-size: 16px;color: red">奖品领取截至日期</strong></h2>
	 </div>
	 <div class="col-xs-offset-1 col-xs-10 text-center"><em><span style="font-size: 16px;" id="luckygetdate"></span></em>
	 </div>
	 </div>
	 </div>
    <div class="container" >  
	 <div id="hexiaodiv" class=sxs  >
	 	 <form class="form-horizontal text-center">
	 	 			<h1 ><strong style="font-size: 26px;">核销验证</strong></h1>
	 	 		  <div class="form-group">
				    <label for="" class="col-xs-12 control-label text-center"><strong style="font-size: 20px;"><span class="press" id="lkuckyinfoname2"></span></strong></label>
				  </div>
				  <div class="form-group">
				    <label for="shopid" class="col-xs-5 control-label text-right"><strong style="font-size: 20px;">店铺编号:</strong></label>
				    <div class="col-xs-7">
				      <input type="number" class="form-control" id="shopid" placeholder="店铺编号">
				    </div>
				  </div>
				  <div class="form-group">
				    <label for="zremark" class="col-xs-5 control-label text-right" style="font-size: 20px;">备注:</label>
				    <div class="col-xs-7">
				      <input type="text" class="form-control" id="zremark" placeholder="备注">
				    </div>
				  </div>
				   <div class="form-group">
				    <label for="usepass" class="col-xs-5 control-label text-right" style="font-size: 20px;">核销密码:</label>
				    <div class="col-xs-7">
				      <input type="text" class="form-control" id="usepass" placeholder="核销密码">
				    </div>
				  </div>
				  <div class="form-group">
				    <div class="col-xs-12 text-center">
				      <button type="button" id="qrButUp" class="btn btn-default">确认核销</button>
				    </div>
				  </div>
				</form>
     </div>
	 
	 <div class="row navbar-fixed-bottom">
	 <div class="col-xs-12" id="butDiv">
	 <input type="button" style="font-size: 22px;" id="butUp"  class="btn btn-info btn-primary btn-lg col-xs-12" value="核销">
	 </div>
	 </div>
	 </div>
		<!-- 
		 -->
<div id="zhezhao" style="display:none;position:absolute;z-index: 9998;top:0px;width:100%;height:100%;background:#f83e3f;">&nbsp;</div>

<!-- 奖品id  可用于获取奖品详细信息显示 -->
<input type="hidden" id="jpid" value="${param.jpid }">
<!-- 获奖信息id  可用于获取奖品核销 -->
<input type="hidden" id="jpgetid" value="${param.jpgetid }">
<input type="hidden" id="shopgetid" value="${param.shopid }">
<input type="hidden" id="getdate" value="${param.getdate }">
<div id="right" onclick="toLuckindex()">
    <p>继续抽奖</p>
</div>
</div>
<script type="text/javascript">
//根据代金券轮次查询此次代金券活动名称和详细说明，背景
	$(document).ready(function(){
		$("#right").hide();
		if($("#shopgetid").val()!=""){
			//$("#butUp") 
			$("#butUp").val("已兑奖")
			$("#butUp").attr("disabled", true); 
		}
		if($("#getdate").val()=="isnow"){
			//$("#butUp")
			//$("#right").show(); 
			$("#butUp").val("继续抽奖");
			$("#butUp").attr("onclick", "toLuckindex()"); 
			$("#butUp").attr("id", "toLuckindex");
			//截止时间
			$.ajax({
				url:"${pageContext.request.contextPath }/luckyWechat_endLuckDate.tony",
				dataType:"html",
				type:"post",
				success:function(msg){
					$("#luckygetdate").html(msg);
				}
			}); 
		}else{
			$("#luckygetdate").html($("#getdate").val());
		}
	});
	$("#butUp").click(function(){
		$("#hexiaodiv").css({"display":"block"});
		$("#zhezhao").css({"display":"block"});
		$("#vouchershowdiv1").css({"display":"none"});
		//alert("弹出核验页面，遮罩");	
	});
	$.ajax({
		url:"${pageContext.request.contextPath }/luckyWechat_queryMyLuckOne.tony",
		data:{"luckyprizeid":$("#jpid").val()},
		datatype:"json",
		type:"post",
		success:function(msg){
			var voucherInfo=eval(msg);
			$("#lkuckyinfoname1").html(voucherInfo[0]);
			$("#lkuckyinfoname2").html(voucherInfo[0]);
			if(voucherInfo[1]==""||voucherInfo[1]==null){
				$("body").css({"background":"#86d6d7"});
				//$("#voucherInfo_img").html("背景暂未设置");
			}else{
			//  imgfile 路径  background:url("../img/Flyer-bg.png") no-repeat;
				$("body").css({"background":"url(\"${pageContext.request.contextPath }/imgfile/"+voucherInfo[1]+"\") repeat-y"});
				$("body").css({"background-size":"100%"});
				//$("#voucherInfo_img").html(voucherInfo[2]);
			}
		}
	});
		function colortext() 
		{ 
		    //获取文字
		    document.getElementById("voucherInfo_name").style.color = getcolor(); 
	    } 
		//设置文字颜色     
		function getcolor() 
		{ 
		    var mycolor = "#"; 
		    var color ="123456789abcdef"; 
		    var colorcode = color.split(""); 
		    for(var i=0;i<6;i++) 
		    { 
		        mycolor+=colorcode[Math.floor(15*Math.random())];        
		    } 
		    return mycolor; 
		} 
		setInterval("colortext()",200);
		
		$("#qrButUp").click(function(){
			var jpgetid=$("#jpgetid").val();
			var shopid=$("#shopid").val();
			var zremark=$("#zremark").val();
			var usepass=$("#usepass").val();
			//alert(useid+"/"+shopid+"/"+ticknum+"/"+zmoney);
			if(shopid==""||shopid==null){
				alert("核销店铺信息不能为空");
			}else{
				$.ajax({
					//提交，如果店铺不存在提示信息，提交成功跳转到成功页面
					url:"${pageContext.request.contextPath }/luckyWechat_addUserInfo.tony",
					data:{"jpgetid":jpgetid,"shopid":shopid,"zremark":zremark,"usepass":usepass},
					dataType:"html",
					type:"post",
					success:function(msg){
						if(msg=="n"){
							alert("使用失败，请重新尝试");
						}else{
							alert("使用成功");
							//window.location.href="${pageContext.request.contextPath }/jsp/page/lucky/jsp/useSuccess.jsp";
							$("#onediv").hide();
							$("body").css("background-size","100%").css("background","url(${pageContext.request.contextPath }/jsp/page/lucky/jsp/images/luckyuse.jpg) repeat-y;");
						}
					
					}
				});
			}
		});  
		//去抽奖页面
		function toLuckindex(){
			window.location.href="${pageContext.request.contextPath }/userwechat_flagWechatLuck.tony";
		}
</script>
 </body>
</html>
