<%@ page pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta name="description"
	content="A multi-page template generated by Tizen Web IDE" />
<title>抽奖统计</title>
<%@include file='/jsp/head.jsp'%>
</head>
<body >
<table width="100%">
	<tr>
		<td width=45% valign="top">
			活动名称：<input type="text" id="zname">		<input type="button" value="查询" class="bt_tony" onclick="findLucky()">
		</td>
		<td width=55% valign="top">
		<div align="center"><b>奖品表</b></div>
		</td>
	</tr>
	<tr>
		<td valign="top">
			<div class="tbdiv" id="myService1" ></div>
		</td>
		<td valign="top">
		<div class="tbdiv" id="myService2" ></div>
		</td>
	</tr>
	<tr>
		<td valign="top">
			<br/>
			<div align="center"><b>（店铺统计）点击看详情</b></div>
			<div class="tbdiv" id="myService3" ></div>
		</td>		
		<td valign="top"><br/>
			<div align="center"><b>（店铺统计）奖品领取详情</b></div><div class="tbdiv" id="myService4" ></div></td>
	</tr>
</table>
<script type="text/javascript">
$(document).ready(function() {
	var sql=sqlobj[3];
 	 initsql(sql);
});
function initsql(sql){
	var objs=["1","5","开始时间#结束时间#抽奖活动名称","30%#30%#40%","",sql,"myService1",getPrizeInfo,0];	
	putPageStrings(objs); 
}
function getPrizeInfo(){
	$("#myService1 table tr:not(:first)").each(function(){
		var zid=$(this).attr("id");
    	$(this).bind("click",function(){//单击
    		showPrizeList(zid);
    	});
 	});
}
function showPrizeList(zid){
	var sql=sqlobj[5];
	sql=sql.replace("1=2", "luckyid="+zid);
	var objs=["1","5","奖品名称#奖品价值#中奖机率#最大发放","50%#20%#15%#15%","",sql,"myService2","",1];	
	putPageStrings(objs); 
	
	sql=sqlobj[6];
	sql=sql.replace(/\luckyid=1/g,  "luckyid="+zid);
	objs=["1","10","店铺编号#已领数#已兑数","32%#34%#34%","",sql,"myService3",showPrizeInfo,2];	
	putPageStrings(objs); 
}
//======点击看详情
function showPrizeInfo(){
	$("#myService3 table tr:not(:first)").each(function(){
		var luckyid=$(this).attr("id");
    	$(this).bind("click",function(){//单击
    		var shopid=$(this).find("td").eq(0).text();
    		showPrizeInfoList(luckyid,shopid);
    	});
 	});
}
function showPrizeInfoList(luckyid,shopid){
	var sql=sqlobj[7];
	sql=sql+" and A.shopid="+shopid+" and A.luckyid="+luckyid;
	var objs=["1","10","奖品名称#领取日期#兑换日期","32%#34%#34%","",sql,"myService4","",3];	
	putPageStrings(objs); 
}
</script>
</body>
</html>