<%@ page pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta name="description"
	content="A multi-page template generated by Tizen Web IDE" />
<title>设置抽奖</title>
<%@include file='/jsp/head.jsp'%>
</head>
<body >
<div align=center>
	<table width=100%>
		<tr>
			<td width=50% valign="top">
				<div class="tbdiv" id="myService1" ></div>
				<br/>				
				<table width=100% class="lrtb" style="border-top: 1px solid #d8d8d8;padding-right: 5px;">
				<caption><b>单击操作奖品，双击修改</b></caption>
					<tr>
						<td width="20%"><font color=red>*</font>活动开始时间</td><td width="30%"><input type="text" name="startdate" id="startdate" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss',skin:'ext'})"></td>
						<td width="20%"><font color=red>*</font>活动结束时间</td><td width="30%"><input type="text" name="enddate" id="enddate" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss',skin:'ext'})"></td>
					</tr>
					<tr>
						<td width="20%"><font color=red>*</font>兑奖开始时间</td><td width="30%"><input type="text" name="luckystart" id="luckystart" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss',skin:'ext'})"></td>
						<td width="20%"><font color=red>*</font>兑奖结束时间</td><td width="30%"><input type="text" name="luckyend" id="luckyend" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss',skin:'ext'})"></td>
					</tr>
					<tr>
						<td><font color=red>*</font>抽奖活动名称</td><td><input type="text" name="zname" id="zname" maxlength="30"></td>		
						<td>是否有效</td><td><select name="zstate" id="zstate"><option value="1">有效</option><option value="0">无效</option></select></td>	
					</tr>
					<tr>
						<td>宣传语言</td><td colspan=3><input type="text" name="zscript" id="zscript" maxlength="300"></td>
					</tr>
					<tr>
						<td>兑奖类型</td><td colspan=2><select name="ztype" id="ztype" onchange="changeTxt(this)"><option value="1">兑奖时间结束时结束兑奖</option><option value="2">兑奖期间每天几点停止抽奖</option></select></td>
						<td></td>
					</tr>
					<tr>						
						<td><font color=red id="txtsn">*</font>最多抽奖次数</td><td><input type="text" name="ztimes" id="ztimes" onkeyup="this.value=this.value.replace(/\D/g,'')"  onafterpaste="this.value=this.value.replace(/\D/g,'')"  maxlength="6"></td>
						<td><font color=red id="txtsn">*</font>兑奖密码</td><td><input type="text" name="usepass" id="usepass"></td>
					</tr>
					<tr>
						<td>备注</td><td colspan=3><input type="text" name="zremark" id="zremark" maxlength="200"></td>
					</tr>
					<tr>
						<td colspan=2  style="text-align: left;"><input type="button" value=" 保 存 " onclick="saveLucky()" class="bt_tony"/></td>
						<td><input type="text" name="notime" id="notime" maxlength="8" onfocus="WdatePicker({dateFmt:'HH:mm:ss',skin:'ext'})" value="${notime }"></td>
						<td><input type="button" value="当天兑奖截止时间 " onclick="saveNotime()" class="bt_tony"/></td>
					</tr>
				</table>
				<input type="hidden" name="zid" id="zid">
				<br/>
				
				<font color="red">${message }</font>
			</td>
			<td width=50% valign="top">
			<div class="tbdiv" id="myService2" ></div>
			<br/>		
			<form action="lucky_savePrize.tony" method="post" enctype="multipart/form-data" id="aform">		
				<table width=100% class="lrtb" style="border-top: 1px solid #d8d8d8;padding-right: 5px;">
				<caption><b>双击修改</b></caption>
					<tr>
						<td width="20%"><font color=red>*</font>奖品名称</td><td width="30%"><input type="text" name="prizename" id="prizename"></td>
						<td width="20%"><font color=red>*</font>奖品价值</td><td width="30%"><input type="text" name="prizemoney" id="prizemoney"  onkeyup="this.value=this.value.replace(/\D/g,'')"  onafterpaste="this.value=this.value.replace(/\D/g,'')"  maxlength="5"></td>
					</tr>
					<tr>
						<td><font color=red>*</font>中奖机率</td><td><input type="text" name="percent" id="percent"  onkeyup="if(isNaN(value))execCommand('undo')" onafterpaste="if(isNaN(value))execCommand('undo')"  maxlength="7"></td>
						<td><font color=red>*</font>最大发放</td><td><input type="text" name="znum" id="znum"  onkeyup="this.value=this.value.replace(/\D/g,'')"  onafterpaste="this.value=this.value.replace(/\D/g,'')"  maxlength="8"></td>
					</tr>
					<tr>
						<td><font color=red>*</font>奖品图片</td><td colspan=3><input type="file" name="zfile" id="zfile"></td>
					</tr>
					<tr>
						<td><font color=red>*</font>中奖是否记录</td><td><select name="istrue" id="istrue"><option value="1">记录</option><option value="0">不记录</option></select></td><td></td><td></td>
					</tr>
					<tr>
						<td valign="top" align="right" colspan="4"><font color="red"> 图片大小，不超过256KB，建议宽600，高900，格式为jpg或gif。</font></td>
					</tr>
					</table>
					<input type="hidden" name="prizezid" id="prizezid">
					<input type="hidden" name="luckyzid" id="luckyzid">
				</form>
				<br/>
				<input type="button" value=" 保 存 " onclick="saveVoucher()" class="bt_tony"/>
				<font color="red">${message2 }</font>
			</td>
		</tr>
	</table>	
</div>
<script type="text/javascript">
$(document).ready(function() {
	  //设置AJAXForm的选项
		    var options = { 
		        success:showResponse,
		        dataType:'script'
		    };		 
		    
		    //绑定gridForm通过AJAX提交
			$('#aform').ajaxForm(options); 
	var sql=sqlobj[3];
 	 initsql(sql);
});
function changeTxt(obj){
	if($(obj).val()=="1"){
		$("#txtsn").text("*");
	}else{
		$("#txtsn").text("*每天");
	}
}
function initsql(sql){
	var objs=["1","6","开始时间#结束时间#抽奖活动名称#次数#状态#0#0#0#0#0#0","25%#25%#34%#8%#8%#0#0#0#0#0#0","",sql,"myService1",getinfoLucky,0];	
	putPageStrings(objs); 
}
function getinfoLucky(){  //单击看奖品，双击修改
	$("#myService1 table tr:not(:first)").each(function(){
		var zid=$(this).attr("id");
    	$(this).bind("dblclick",function(){  //双击修改
    		modifylucky(zid,this);
    	}).bind("click",function(){//单击
    		showPrize(zid);
    	});
 	});
}
function showPrize(zid){//单击看奖品
	$("#luckyzid").val(zid);
	var sql=sqlobj[4];
	sql=sql.replace("1=2", "luckyid="+zid);
	var objs=["1","6","奖品名称#奖品图片#奖品价值#中奖机率#最大发放","30%#37%#11%#11%#11%","",sql,"myService2",modifyPrize,1];	
	putPageStrings(objs); 
}
function saveLucky(){
	var zid=$("#zid").val();
	var startdate=$("#startdate").val();
	var enddate=$("#enddate").val();
	var zname=$("#zname").val();
	var zscript=$("#zscript").val();
	var ztimes=$("#ztimes").val();
	var zstate=$("#zstate").val();
	var luckystart=$("#luckystart").val();var luckyend=$("#luckyend").val();var ztype=$("#ztype").val();var zremark=$("#zremark").val();var usepass=$("#usepass").val();
	var temp=validateFormInput("startdate,enddate,zname,ztimes,luckystart,luckyend,usepass","开始时间,结束时间,抽奖活动名称,最多抽奖次数,兑奖开始时间,兑奖结束时间,兑奖密码",",");
	if(temp==""){
		B = ui.box("请稍等......", waitHtml, false, true, function(a, b) {	}, [ 200, 100 ]);
		$.ajax({
		   type: "POST",
		   url: "lucky_saveLucky.tony",
		   dataType:"json",
		   data: {
			   "zid":zid,
				"startdate":startdate,
				"enddate":enddate,
				"zname":zname,
				"zscript":zscript,
				"ztimes":ztimes,
				"zstate":zstate,
				"luckystart":luckystart,
				"luckyend":luckyend,
				"ztype":ztype,
				"zremark":zremark,
				"usepass":usepass
			},
		   success: function(msg){
		   		B.close();
				if(msg=="1"){			
					clearLuck();		
					var sql=sqlobj[3];
 	 				initsql(sql);
					ui.alert("恭喜您，保存成功！",800);
				}else{
					ui.alert("对不起，保存失败，请重试！",900);
				}  
		   }
	});
	}else{
		ui.alert("对不起，以下录入框不能为空：\n"+temp);
	}
}
function clearLuck(){
	$("#zid").val("");
	$("#startdate").val("");
	$("#enddate").val("");
	$("#zname").val("");
	$("#zscript").val("");
	$("#ztimes").val("");
	$("#zstate").val("");
	$("#luckystart").val("");
	$("#luckyend").val("");
	$("#zremark").val("");
	$("#ztype").val("1");
	$("#usepass").val("");
}
function modifylucky(zid,obj){//双击修改
	var tr=$(obj).find("td");
	$("#zid").val(zid);
	$("#startdate").val(tr.eq(0).text());
	$("#enddate").val(tr.eq(1).text());
	$("#zname").val(tr.eq(2).text());
	$("#zscript").val(tr.eq(4).find("input").eq(0).val());
	$("#luckystart").val(tr.eq(4).find("input").eq(1).val());
	$("#luckyend").val(tr.eq(4).find("input").eq(2).val());
	$("#ztype").val(tr.eq(4).find("input").eq(3).val());
	$("#zremark").val(tr.eq(4).find("input").eq(4).val());
	$("#usepass").val(tr.eq(4).find("input").eq(5).val());
	$("#ztimes").val(tr.eq(3).text());
	if(tr.eq(4).text().substring(0,2)=="有效")
		$("#zstate").val("1");
	else
		$("#zstate").val("0");
}
function saveVoucher(){
	if($("#luckyzid").val()!=""){
		var temp=validateFormInput("prizename,prizemoney,percent,znum","奖品名称,奖品价值,中奖机率,最大发放",",");
		if(temp==""){
			var percent=$("#percent").val();
			if(Number(percent)>1){
				ui.alert("对不起，中奖机率必须小于等于一！",1000);
				$("#percent").css("border","1px solid red");
			}else{
				B = ui.box("请稍等......", waitHtml, false, true, function(a, b) {	}, [ 200, 100 ]);
				$("#aform").submit();
			}
		}
	}else{
		ui.alert("请点击左边的抽奖活动！",800);
	}
}
function modifyPrize(){  //修改奖品
	$("#myService2 table tr:not(:first)").each(function(){
    	$(this).bind("dblclick",function(){  //双击修改
    		modifyCurPrize(this);
    	});
 	});
}
function showResponse(responseText){
		B.close();
			if(responseText=="1"){
				clearForm("aform","prizezid");				
				var zid=$("#luckyzid").val();
				showPrize(zid);	
				ui.alert("保存成功！",800);
			}else{				
				ui.alert("对不起，保存失败！",800);
			}
}
function modifyCurPrize(obj){
	$("#prizezid").val($(obj).attr("id"));
	var tr=$(obj).find("td");
	$("#prizename").val(tr.eq(0).text());
	$("#prizemoney").val(tr.eq(2).text());
	$("#percent").val(tr.eq(3).text());
	$("#znum").val(tr.eq(4).text());
}
function saveNotime(){
	var notime=$("#notime").val();
	if(notime==""){
		alert("请您选择时间！");
	}else{
		$.ajax({
		   type: "POST",
		   url: "lucky_saveNotime.tony",
		   data: {
			   "notime":notime
			},
		   success: function(msg){
		   	if(msg=="1")
		   		ui.alert("恭喜您设置成功！",800);
		   }
	});
	}
}
</script>
</body>
</html>