<%@ page pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta name="description"
	content="A multi-page template generated by Tizen Web IDE" />
<title>设置代金券</title>
<%@include file='/jsp/head.jsp'%>
</head>
<body >
<table width="100%">
	<tr>
		<td>
			名称：<input type="text" id="zname">		<input type="button" value="查询" class="bt_tony" onclick="findVocher()">
			<b>双击行统计使用情况</b>
			<input type="button" value="刷新" class="bt_tony" onclick="findVocher()">
		</td>
		<td align=center>
			<b>代金券领取情况</b>
		</td>
	</tr>
	<tr>
		<td width="60%" valign="top">
			<div class="tbdiv" id="myService1" ></div>
		</td>
		<td width="40%" valign="top">
			<div class="tbdiv" id="myService2" ></div>
		</td>
	</tr>
	<tr>
		<td></td>
		<td id="usedtj"></td>
	</tr>
	<tr>
		<td valign="top" align="center" style="border: 1px solid #d8d8d8;padding-top: 10px;padding-bottom: 6px;"><b>各个店铺使用详情</b></td>
		<td valign="top" align="center" style="border: 1px solid #d8d8d8;padding-top: 10px;padding-bottom: 6px;"><b>各个店铺使用统计(《双击看详情)</b></td>
	</tr>
	<tr>
		<td valign="top"><div class="tbdiv" id="myService3" ></div></td>
		<td valign="top"><div class="tbdiv" id="myService4" ></div></td>
	</tr>
</table>
<script type="text/javascript">
var currentzid=0;
$(document).ready(function() {
	var sql=sqlobj[0];
 	 initsql(sql);
});
function findVocher(){
	var zname=$("#zname").val();
	var sql=sqlobj[0];
	if(zname!=""){		
		sql=sql.replace("1=1", " zname like '%"+zname+"%' ");		
	}
	 initsql(sql);
}
function initsql(sql){
	var objs=["1","6","名称#开始时间#结束时间#数量#状态#操作","20%#29%#29%#7%#7%#8%","",sql,"myService1",getUsed,0];	
	putPageStrings(objs); 
}
function getUsed(){
	$("#myService1 table tr:not(:first)").each(function(){
		var zid=$(this).attr("id");
    	$(this).bind("dblclick",function(){
    		getInfoUser(zid)
    	});
 	});
}
function modifyCoucher(obj){
	var zid=$(obj).closest("tr").attr("id");		
	var r=window.open("coucher_modifyCoucher.tony?zid="+zid, "","width=660,height=350");
}
function getInfoUser(zid){
	currentzid=zid;
	B = ui.box("请稍等......", waitHtml, false, true, function(a, b) {	}, [ 200, 100 ]);
	var sql=sqlobj[1];
	sql=sql.replace("1=2", "voucherid="+zid);
	var objs=["1","6","领取时间#状态#金额","50%#20%#30%","",sql,"myService2",tjnum,1];	
	putPageStrings(objs); 
	
}
function tjnum(){
	if(currentzid!=""){
		$.ajax({
			   type: "POST",
			   url: "coucher_tjGetVocher.tony",
			   data: {"zid":currentzid},
			   success: function(msg){
					$("#usedtj").html(msg);	
					getShopUse();	
			   }
		});
	}
}
function getShopUse(){
	var sql=sqlobj[2]+" AND B.voucherid="+currentzid;
	var objs=["1","6","店铺ID#使用时间#小票编号#小票金额#使用金额","20%#25%#25%#15%#15%","",sql,"myService3",shopTj,2];	
	putPageStrings(objs); 	
}

function shopTj(){
	$.ajax({
			   type: "POST",
			   url: "coucher_shopTj.tony",
			   data: {"zid":currentzid},
			   success: function(msg){
					$("#myService4").html(msg);	
					B.close();
			   }
		});
}
function showShopInfo(shopid){
	var sql=sqlobj[2]+" AND B.voucherid="+currentzid+" and A.shopid="+shopid;
	var objs=["1","6","店铺ID#使用时间#小票编号#小票金额#使用金额","20%#25%#25%#15%#15%","",sql,"myService3","",2];	
	putPageStrings(objs); 	
}
</script>
</body>
</html>