<%@ page pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta name="description"
	content="A multi-page template generated by Tizen Web IDE" />
<title>设置代金券</title>
<%@include file='/jsp/head.jsp'%>
</head>
<body >
<div align=center>
<form action="coucher_saveCoucher.tony" method="post" enctype="multipart/form-data" id="aform"> 
	<table width=600 class="lrtb">
		<tr>
			<td width="100"><font color=red>*</font>开始时间</td><td width="200"><input type="text" name="startdate" id="startdate" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss',skin:'ext'})"></td>
			<td width="100"><font color=red>*</font>结束时间</td><td width="200"><input type="text" name="enddate" id="enddate" onfocus="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss',skin:'ext'})"></td>
		</tr>
		<tr>
			<td><font color=red>*</font>代金券名称</td><td><input type="text" name="zname" id="zname" maxlength="30"></td>
			<td><font color=red>*</font>发放数量</td><td><input type="text" name="zcount" id="zcount" onkeyup="this.value=this.value.replace(/\D/g,'')"  onafterpaste="this.value=this.value.replace(/\D/g,'')"  maxlength="6"></td>
		</tr>
		<tr>
			<td>最小金额</td><td><input type="text" name="minmoney" id="minmoney" onkeyup="this.value=this.value.replace(/\D/g,'')"  onafterpaste="this.value=this.value.replace(/\D/g,'')"  maxlength="4"></td>
			<td><font color=red>*</font>最大金额</td><td><input type="text" name="maxmoney" id="maxmoney" onkeyup="this.value=this.value.replace(/\D/g,'')"  onafterpaste="this.value=this.value.replace(/\D/g,'')"  maxlength="4"></td>
		</tr>
		<tr>
			<td>代金券模式</td><td><select name="zstyle" id="zstyle"><!-- <option value="1">1:按时发放，过期无效(时间段内有效，无限制使用)</option> -->
					<option value="2">2：无时间限制，使用后无效</option><option value="3" selected="selected">3：过期或使用后无效（一次性）</option></select></td>
			<td>是否有效</td><td><select name="zstate" id="zstate"><option value="1">有效</option><option value="0">无效</option></select></td>
		</tr>
		<tr>
			<td>宣传言语</td><td colspan=3><input type="text" name="zcontent" id="zcontent" maxlength="500"></td>
		</tr>
		<tr>
			<td>代金券背景图</td><td colspan=3><input type="file" name="zfile"></td>
		</tr>
		<tr>
			<td align=right colspan="2"><font color=red>*</font>消费金额满￥&nbsp; <input type="number" value="1" name="usewhere" id="usewhere" onkeyup="this.value=this.value.replace(/\D/g,'')"  onafterpaste="this.value=this.value.replace(/\D/g,'')"  maxlength="4">&nbsp;&nbsp;可以使用</td>
			<td>核销密码</td><td><input type="text" name="usepass" id="usepass" maxlength="19"></td>
		</tr>
		<tr>
			<td colspan=4><font color=red>图片大小，不超过256KB，建议宽600，高900，格式为jpg或gif。</font></td>
		</tr>
	</table>
	<input type="hidden" name="zid" id="zid">
	</form>
	<br/>
	<input type="button" value=" 保 存 " onclick="saveVoucher()" class="bt_tony"/>
	<font color="red">${message }</font>
</div>
<script type="text/javascript">
function initfrm(){
	var pagestr="${pagestr}";
	if(pagestr!=""){
		var ss=pagestr.split("`");
		//startdate,enddate,zname,zcontent,maxmoney,minmoney,zcount,zstyle,zstate,zid
		$("#startdate").val(ss[0]);
		$("#enddate").val(ss[1]);
		$("#zname").val(ss[2]);
		$("#zcontent").val(ss[3]);
		$("#maxmoney").val(ss[4]);
		$("#minmoney").val(ss[5]);
		$("#zcount").val(ss[6]);
		$("#zstyle").val(ss[7]);
		$("#zstate").val(ss[8]);
		$("#zid").val(ss[9]);
		$("#usewhere").val(ss[10]);
	}
}
 initfrm();
 function saveVoucher(){
 	//验证表格录入（"，中文说明集合，分隔符）
 	var text= validateFormInput("startdate,enddate,zname,zcount,maxmoney,usewhere","开始时间,结束时间,代金券名称,发放数量,最大金额,消费金额",",");
 	if(text==""){
 		B = ui.box("请稍等......", waitHtml, false, true, function(a, b) {	}, [ 200, 100 ]);
 		$("#aform").submit();
 	}else{
 		ui.alert("对不起，以下录入框不能为空！<br>"+text,1200);
 	}
 	
 }
</script>
</body>
</html>