<%@ page pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta name="description"
	content="A multi-page template generated by Tizen Web IDE" />
<title>我的代金券</title>
<link href="${pageContext.request.contextPath }/css/bootstrap.min.css" rel="stylesheet" type="text/css"></link>
<%@include file='/jsp/head.jsp'%>
<script type="text/javascript" src="${pageContext.request.contextPath }/jsp/page/voucher/jsp/js/browser.js"></script>
<style type="text/css">
@-moz-document url-prefix() {
  fieldset { display: table-cell; }
}
.container{
padding-top: 80%;
width: 95%;

}
.table-responsive{height: 200px;overflow:auto;border:1px solid #d90b03;background:#fff}

html,body{height :100%;}
</style>
</head>

<body style="position:absolute; width:100%; height:100%; z-index:-1;background:url(${pageContext.request.contextPath }/jsp/page/voucher/jsp/images/221.jpg) repeat-y;background-size:100% 100%">
<div class="container" >  
		 <div class="row">
			 <div class="col-xs-12">
			 &nbsp;
	 	 	 </div>
	 </div>
	 <div class="row">
	 <div class="col-xs-offset-1 col-xs-10">
		 <h3 class="text-center " style="font-size: 21px;color: #fff">代金券</h3>
	 </div>
	 </div>
	<div>
	<div class="row">
	 <div class="col-xs-offset-1 col-xs-10">
	<br>
		</div>
	 </div>
	 <div class="row">
	 <div class="table-responsive">
		<table class="table table-striped" id="myCoucherList"> 
		
		 </table>
		</div>
		 
	 </div>
	</div></div>
	<div style="color: #fff;margin-top: -4%;margin-left: 19%">本活动最终解释权归：信阳百家公司所有</div>
<script type="text/javascript">
	$(document).ready(function(){
		$.ajax({
				//提交，如果店铺不存在提示信息，提交成功跳转到成功页面
				url:"${pageContext.request.contextPath }/coucherWechat_queryMyCoucherList.tony",
				dataType:"html",
				type:"post",
				success:function(msg){
					if(msg==""){
						$("#myCoucherList").html('您暂无代金券，<a href="${pageContext.request.contextPath }/coucherWechat_checkCoucherIshave.tony">点我领取</a>');
					}else{
						var voucherInfo=eval(msg);
						var voucherInfohtml='';
						for ( var num in voucherInfo) {
							voucherInfohtml=voucherInfohtml+'<tr><td>金额：'+voucherInfo[num][4]+'</td><td>领取日期：'+voucherInfo[num][2]+'</td><td>';
							if(voucherInfo[num][3]==0){
								voucherInfohtml=voucherInfohtml+'已失效';
							}else if(voucherInfo[num][3]==2){
								voucherInfohtml=voucherInfohtml+'已使用';
							}else{
								voucherInfohtml=voucherInfohtml+'<a href="${pageContext.request.contextPath }/coucherWechat_queryMyCoucherOne.tony?zid='+voucherInfo[num][0]+'">点我使用</a>';
							}
							voucherInfohtml=voucherInfohtml+'</td> </tr>';
						}
						$("#myCoucherList").html(voucherInfohtml);
					}
				},
				error:function(){
					$("#myCoucherList").html('您暂无代金券，<a href="${pageContext.request.contextPath }/coucherWechat_checkCoucherIshave.tony">点我领取</a>');
				}
		});
	});
</script>
</body>
</html>