<%@ page pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta name="description"
	content="A multi-page template generated by Tizen Web IDE" />
<title>代金券</title>
<%@include file='/jsp/head2.jsp'%>
<script type="text/javascript" src="${pageContext.request.contextPath }/jsp/page/voucher/jsp/js/browser.js"></script>
<style type="text/css">

body {height: 100%;}
</style>
</head>
<!-- $("body").css({"background":"url(\"${pageContext.request.contextPath }/imgfile/"+voucherInfo[2]+"\") repeat-y"});
				$("body").css({"background-size":"100%"}); -->
<body style="background:url(${pageContext.request.contextPath }/jsp/page/voucher/jsp/images/nohave.jpg) repeat-y;background-size:100%">
  </body>
</html>
