<%@ page pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta name="description"
	content="A multi-page template generated by Tizen Web IDE" />
<title>代金券</title>
<link href="${pageContext.request.contextPath }/css/bootstrap.min.css" rel="stylesheet" type="text/css"></link>
<%@include file='/jsp/head2.jsp'%>
<script type="text/javascript" src="${pageContext.request.contextPath }/jsp/page/voucher/jsp/js/browser.js"></script>
<style>
	#voucherInfo_name{
		font-size: 25px;
	}
	.press{
		color: transparent;
		-webkit-text-stroke: 1px black;
		font-size:24px;
		font-style: oblique;
		letter-spacing: 0.05em;
	}
	#hexiaodiv{
	  display:none;
	  position:absolute;
	  top:25px;
	  z-index:9999;
	}
	#vouchershowdiv{ display:inline-block; position:relative; margin:50px; padding:20px; background:#fafafa; box-shadow:0 0 3px rgba(0, 0, 0, 0.2); -moz-border-radius:4px; border-radius:4px; color:rgba(0,0,0, 0.8); text-shadow:0 1px 0 #fff;}  
	#vouchershowdiv::before, #vouchershowdiv::after{ position:absolute; content:""; top:10px; bottom:15px; left:10px; width:50%; box-shadow:0 15px 10px rgba(0, 0, 0, 0.5); -webkit-transform: rotate(-3deg); -moz-transform:rotate(-3deg); -o-transform:rotate(-3deg); -ms-transform:rotate(-3deg); transform:rotate(-3deg); z-index:-1;}  
	#vouchershowdiv::after{ right:10px; left:auto; -webkit-transform:rotate(3deg); -moz-transform:rotate(3deg); -o-transform:rotate(3deg); -ms-transform:rotate(3deg); transform: rotate(3deg);}  
	#vouchershowdiv img{ vertical-align:bottom;} 
	body {height: 100%;}
	
#vouchershowdiv1{
margin-top:23%;
width:86%; 
height:330px; 
background:url(${pageContext.request.contextPath }/jsp/page/voucher/jsp/images/1.png);
background-size:100% 100%;
}
.sxs{
float:left;
position:absolute; 
width:100%; 
height:100%; 
background:url(${pageContext.request.contextPath }/jsp/page/lucky/jsp/images/dphx.jpg);
background-size:100% 100%;
margin-left: -8%;
padding-top: 19%;
	}
 #butDiv{
 background-color: #39ee0f;
 
 }
</style>
</head>
<body >
<div id="onediv">
	 <div class="container" id="vouchershowdiv1">  
	 <div class="ol"><div class="row" style="padding-top:27%">
	 <div class="col-xs-offset-1 col-xs-10">
		 <h3 class="text-center "><span id="voucherInfo_name"></span></h3>
	 </div>
	 </div>
	 <div class="row"  style="padding-top:5%">
	 <div class="col-xs-offset-1 col-xs-10" style="text-align: center;">
		 <em class="text-center">&nbsp;&nbsp;&nbsp;&nbsp;<span id="voucherInfo_content" style="font-size: 18px;color: #fff;"></span></em>
	 </div>
	 </div>
	 <div class="row">
	 <div class="col-xs-offset-1 col-xs-10">
		 <h2 class="text-center"><strong style="font-size: 20px;color: #fff;">代金券领取日期</strong></h2>
	 </div>
	 <div class="col-xs-offset-1 col-xs-10 text-center"><em><span style="font-size: 16px;color: #fff;">${stringVoucher[1] }</span></em>
	 </div>
	 </div>
	 <div class="row">
	 <div class="col-xs-offset-1 col-xs-10">
		 <h2 class="text-center"><strong style="font-size: 20px;color: #fff;">代金券金额：</strong><span class="press" style="color: #fff;">${stringVoucher[3] }</span>元</h2>
	 </div>
	 </div></div>
	 </div>
	  <div class="container">  
	 <div id="hexiaodiv" class=sxs>
	 	 <form class="form-horizontal text-center">
	 	 			<h1 ><strong style="font-size: 26px;">核销验证</strong></h1>
	 	 		  <div class="form-group">
				    <label for="shopid" class="col-xs-7 control-label text-right"><strong style="font-size: 20px;">代金券金额</strong></label>
				    <div class="col-xs-4">
				     <span class="press">${stringVoucher[3] }</span>元
				    </div>
				  </div>
				  <div class="form-group">
				    <label for="shopid" class="col-xs-5 control-label text-right"><strong style="font-size: 20px;">店铺编号:</strong></label>
				    <div class="col-xs-7">
				      <input type="number" class="form-control" id="shopid" placeholder="店铺编号">
				    </div>
				  </div>
				  <div class="form-group">
				    <label for="ticknum" class="col-xs-5 control-label text-right" style="font-size: 20px;"  onclick="addlsh()">流水号(<font style="color: #fff;font-size: 22px;font-weight: bold;" >+</font>):</label>
				    <div class="col-xs-7">
				      <input type="number" class="form-control" name="ticknum" id="ticknum" placeholder="流水号">
				    </div>
				  </div>
				  <div class="form-group">
				    <label for="zmoney" class="col-xs-5 control-label text-right" style="font-size: 20px;">小票总金额:</label>
				    <div class="col-xs-7">
				      <input type="number" class="form-control" id="zmoney" placeholder="小票金额">
				    </div>
				  </div>
				  <div class="form-group">
				    <label for="zmoney" class="col-xs-5 control-label text-right" style="font-size: 20px;">核销密码:</label>
				    <div class="col-xs-7">
				      <input type="number" class="form-control" id="usepass" placeholder="核销密码">
				    </div>
				  </div>
				  <div align="center">消费金额满￥<font style="color: #fff;font-size: 22px;font-weight: bold;" id="xzmoney" >${stringVoucher[5] }</font> 可以使用</div>
				  <div class="form-group">
				    <div class="col-xs-12 text-center">
				      <button type="button" id="qrButUp" class="btn btn-default">确认核销</button>
				    </div>
				  </div>
				</form>
     </div>
	 
	 <div class="row navbar-fixed-bottom">
	 <div class="col-xs-12" id="butDiv">
	 <input type="button" style="font-size: 22px;background-color:#f83151 " id="butUp"  class="btn btn-info btn-primary btn-lg col-xs-12" value="核销">
	 </div>
	 </div>
	 </div>
		 <div id="zhezhao" style="display:none;position:absolute;z-index: 9998;top:0px;width:100%;height:100%;background:#f83e3f;">&nbsp;</div>

<input type="hidden" id="voucherInfo_style" value="">	 
<input type="hidden" id="voucherstate" value="${stringVoucher[2] }">	 
<input type="hidden" id="voucheruseid" value="${stringVoucher[0] }">
<input type="hidden" id="voucherid" value="${stringVoucher[4] }">
</div>
<script type="text/javascript">
//根据代金券轮次查询此次代金券活动名称和详细说明，背景
	$(document).ready(function(){
		 init();
		if($("#voucherstate").val()==0){
			$("#butUp").val("该券已失效")
			$("#butUp").attr("disabled", true); 
		}if($("#voucherstate").val()==2){
			$("#butUp").val("该券已使用")
			$("#butUp").attr("disabled", true); 
		}
	});
	$("#butUp").click(function(){
		$("#vouchershowdiv1").hide();
		$("#hexiaodiv").show();
		$("#zhezhao").show();
	});
	function init(){
			$.ajax({
				url:"${pageContext.request.contextPath }/coucherWechat_coucherInfo.tony",
				data:{"voucherid":$("#voucherid").val()},
				datatype:"json",
				type:"post",
				success:function(msg){
					var voucherInfo=eval(msg);
					$("#voucherInfo_name").html(voucherInfo[0]);
					$("#voucherInfo_content").html(voucherInfo[1]);
					if(voucherInfo[2]==""||voucherInfo[2]==null){
						$("body").css({"background":"#F6D2C4"});
						//$("#voucherInfo_img").html("背景暂未设置");
					}else{
						$("body").css({"background":"url(\"${pageContext.request.contextPath }/imgfile/"+voucherInfo[2]+"\") no-repeat"});
						$("body").css({"background-size":"100%"});
					}
					$("#voucherInfo_style").val(voucherInfo[3]);
				}
			});
		}
		function colortext() 
		{ 
		    //获取文字
		    document.getElementById("voucherInfo_name").style.color = getcolor(); 
	    } 
		//设置文字颜色     
		function getcolor() 
		{ 
		    var mycolor = "#"; 
		    var color ="123456789abcdef"; 
		    var colorcode = color.split(""); 
		    for(var i=0;i<6;i++) 
		    { 
		        mycolor+=colorcode[Math.floor(15*Math.random())];        
		    } 
		    return mycolor; 
		} 
		setInterval("colortext()",200);
		
		$("#qrButUp").click(function(){
			var useid=$("#voucheruseid").val();
			var shopid=$("#shopid").val();
			var ticknum="";
			$("input[name='ticknum']").each(function(){
				if($(this).val()!="")
					ticknum=ticknum+$(this).val()+",";
			});
			var zmoney=$("#zmoney").val();
			var xzmoney=$("#xzmoney").text();
			if(Number(zmoney)<Number(xzmoney)){
				alert("对不起，您的消费金额小于代金券使用限制，您不能使用该代金券！");
			}else{
				var voucherInfo_style=$("#voucherInfo_style").val();
			//alert(useid+"/"+shopid+"/"+ticknum+"/"+zmoney);
			if(useid==""||useid==null||shopid==""||shopid==null||ticknum==""||ticknum==null){
				alert("核销信息不能为空");
			}else{
				var usepass=$("#usepass").val();
					$.ajax({
						//提交，如果店铺不存在提示信息，提交成功跳转到成功页面
						url:"${pageContext.request.contextPath }/coucherWechat_addUserInfo.tony",
						data:{"useid":useid,"shopid":shopid,"ticknum":ticknum,"zmoney":zmoney,"voucherInfo_style":voucherInfo_style,"usepass":usepass},
						dataType:"html",
						type:"post",
						success:function(msg){
							if(msg==null || msg=="null"){
								alert("使用失败，请重新尝试");
								window.location.href="${pageContext.request.contextPath }/coucherWechat_checkCoucherIshave.tony";
							}else if(msg=="1"){
								alert("对不起，您的核销密码不对！");
							}else{
								alert("使用成功");
								//window.location.href="${pageContext.request.contextPath }/jsp/page/voucher/jsp/useSuccess.jsp";
								$("#onediv").hide();
								$("body").css("background-size","100%").css("background","url(${pageContext.request.contextPath }/jsp/page/voucher/jsp/images/usesuccess.jpg) repeat-y;");
							}
						
						}
					});
				}
			}			
		});  
		function addlsh(){
			$("#ticknum").before("<input type='number' class='form-control' name='ticknum' placeholder='流水号'>");
		}
</script>
 </body>
</html>
