<%@ page pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta name="description"
	content="A multi-page template generated by Tizen Web IDE" />
<title>已领取</title>
</head>
<body  style="background:url(${pageContext.request.contextPath }/jsp/page/voucher/jsp/images/12.jpg) repeat-y;background-size:100%">

</body>
</html>