<%@ page pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport"
	content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta name="description"
	content="A multi-page template generated by Tizen Web IDE" />
<title>活动即将到来</title>
<%@include file='/jsp/head2.jsp'%>
<script type="text/javascript" src="${pageContext.request.contextPath }/jsp/page/voucher/jsp/js/browser.js"></script>
<style type="text/css">

body {height: 100%;}
</style>
</head>
<body>
<div id="background" style="position:absolute;z-index:-1;width:100%;height:100%;top:0px;left:0px;">
<img src="${pageContext.request.contextPath }/jsp/page/voucher/jsp/images/notime.jpg" width="100%" height="100%"/></div>
  </body>
</html>
